In [7]:
import boto3
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.multiclass import OneVsOneClassifier
from sklearn.metrics import confusion_matrix, classification_report

#defining the bucket
s3 = boto3.resource('s3')
bucket_name = 'rachaeld-data445'
bucket = s3.Bucket(bucket_name)

#defining the csv file
file_key = 'Iris.csv'

bucket_object = bucket.Object(file_key)
file_object = bucket_object.get()
file_content_stream = file_object.get('Body')

iris = pd.read_csv(file_content_stream)
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [8]:
## changing ;abels to numbers
iris['Species_numb'] = np.where(iris['Species'] == 'Iris-virginica',1,
                                np.where(iris['Species'] == 'Iris-versicolor',2,3))
iris.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,Species_numb
0,1,5.1,3.5,1.4,0.2,Iris-setosa,3
1,2,4.9,3.0,1.4,0.2,Iris-setosa,3
2,3,4.7,3.2,1.3,0.2,Iris-setosa,3
3,4,4.6,3.1,1.5,0.2,Iris-setosa,3
4,5,5.0,3.6,1.4,0.2,Iris-setosa,3

In [9]:
## defining inputs and target
X = iris.drop(columns = ['Id', 'Species', 'Species_numb'], axis = 1)
Y = iris['Species_numb']

#splitting the data into train and test
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = .2, stratify = Y)

In [10]:
##scaling the data
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [11]:
### ONE-VS-ONE (LOGISTIC REGRESSION) ###

##building the model 
one_vs_one_LR = OneVsOneClassifier(estimator = LogisticRegression()).fit(X_train,Y_train)

##predicting on the test
one_vs_one_LR_pred = one_vs_one_LR.predict(X_test)

print(confusion_matrix(Y_test, one_vs_one_LR_pred))
print(classification_report(Y_test, one_vs_one_LR_pred))

[[ 9  1  0]
 [ 1  9  0]
 [ 0  0 10]]
              precision    recall  f1-score   support

           1       0.90      0.90      0.90        10
           2       0.90      0.90      0.90        10
           3       1.00      1.00      1.00        10

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30

In [12]:
### ONE-VS-ONE (DECISION TREE) ###

##building the model 
one_vs_one_tree = OneVsOneClassifier(estimator = DecisionTreeClassifier(max_depth = 3)).fit(X_train,Y_train)

##predicting on the test
one_vs_one_tree_pred = one_vs_one_tree.predict(X_test)

print(confusion_matrix(Y_test, one_vs_one_tree_pred))
print(classification_report(Y_test, one_vs_one_tree_pred))

[[ 8  2  0]
 [ 1  9  0]
 [ 0  0 10]]
              precision    recall  f1-score   support

           1       0.89      0.80      0.84        10
           2       0.82      0.90      0.86        10
           3       1.00      1.00      1.00        10

    accuracy                           0.90        30
   macro avg       0.90      0.90      0.90        30
weighted avg       0.90      0.90      0.90        30

In [ ]:
## based on my above results I would pick the first model, the logistic regression, because it has less misclassifications compared to
## the decision tree model to predict Iris species.